### ISSUE TITLE
How to do a single test?

### ISSUE THREAD

**Issue by paul-hammant** [JetBrains/spek#410] opened 2018-05-13 14:15 UTC
Other frameworks allow you to prefix with `only().it(...)` or `only().describe(...)`

How does that work in Spek ?

**Comment by lewismorgan** [comment] 2018-05-15 20:45
Do you mean running just a single test? You can group your tests in "describe", "on", and "it". Each one can be run by itself without running all the tests in the class, unless it's the parent of the test from my understanding. There is gutter icons in the IntelliJ IDE that you can use to run if you're using the plugin. Looks like the IDE runs a spek tooling class. Here's a cutdown version of the console output.

`org.jetbrains.spek.tooling.MainKt --spec com.mydomain.TestingSpek --path "path2speklambda"`

Like I said, I recommended looking at that class to see how it works and to know exactly what Path is expecting using the plugin. I'm not sure if there is one for running without the plugin or not.

**Comment by paul-hammant** [comment] 2018-05-16 12:39
If I'm in Intellij, I presume I can customer the test-runner to pass those `--spec` and `--path` options to the executer.  If from Maven, it'd be `-Dpath=path2speklambda`, right?

I'm asking because I have hundreds of nested describes, and its, and for experimental purposes I'm wanting to run just one without commenting out others, or rearranging the source significantly to facilitate my temporary need.

Same thought from a different angle here - https://github.com/raniejade/spek-idea-plugin/issues/66

**Comment by raniejade** [comment] 2018-05-18 07:09
We have `f` prefixed versions of the scopes (`fit`, `fdescribe`, etc...) which is the same as `only().`, but was dropped in `1.1`. We felt it was a hacky solution for frameworks who don't have any good IDE support. 

Closing this as it is a duplicate of #285 .

**Closed as completed by raniejade** 2018-05-18 07:09 UTC
