### ISSUE TITLE
[Feature Request] Structure dialog contents

### ISSUE THREAD

**Issue by danielgomezrico** [JetBrains/spek#918] opened 2020-08-27 19:33 UTC
It will be cool to allow that intellij understands the spek files and prints the structure in the structure tree.

I show here that it does not print anything:

![image](https://user-images.githubusercontent.com/76348/91486568-14bbf700-e872-11ea-99b3-7bf5a30cc1be.png)

I found this interesenting when you have multiple tests and to give a broad view on it, it works like that on intelli and flutter on the "flutter outline" form:

![image](https://user-images.githubusercontent.com/76348/91486708-46cd5900-e872-11ea-9180-dfb07b24627e.png)

**Comment by raniejade** [comment] 2020-10-02 07:20
Closing as a duplicate of #790. I did some initial investigations before, the structured view is tied to the language of the file and it's not very easy to extend. Most probably, I'm going to add a new tool windows for this.

**Closed as completed by raniejade** 2020-10-02 07:20 UTC
Labels: status: triage
