### ISSUE TITLE
Spek tests not runnable from Maven

### ISSUE THREAD

**Issue by RuudPaulissen** [JetBrains/spek#224] opened 2017-07-07 06:54 UTC
I've been trying to get Spek to run from Maven for over a day now. I've followed all guides and examples I could find on the internet, but with no luck. I can run them in my IDE (IntelliJ), manually, but cannot get them to automatically run in bulk.

The documentation on how to run Spek from Maven on the official website, is very incomplete in my opinion (http://spekframework.org/docs/latest/#_maven). The <type>pom</type> has to be removed to allow compilation even.

Can anyone lend me a hand on this please? I've attached my entire pom.xml file (but have removed some private values). My tests/specifications have classnames of the form "...Spec.kt".
[pom.xml.zip](https://github.com/JetBrains/spek/files/1130206/pom.xml.zip)

Thanks in advance!
- Ruud

**Comment by RuudPaulissen** [comment] 2017-07-07 09:19
On a sidenote: I _was_ able to run my test manually. Spek just stops working now and throws me a nice "Test framework quit unexpectedly".

**Comment by raniejade** [comment] 2017-07-07 10:11
@RuudPaulissen have you checked https://github.com/spekframework/spek-maven-sample?

**Comment by RuudPaulissen** [comment] 2017-07-07 10:38
@raniejade I just got it working again. I was using JUnit platform version 1.0.0-M5 instead of M4. (Please mind that the documentation page to which the Spek docs link you under the "Maven" section, being http://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven, specifies version 1.0.0-M5 as well - this is confusing.)

I don't seem to need the junit-jupiter-engine to run it, either. Or maybe I'm not using any features of it, and that's why it allows me to run the tests without.

Thank you for taking the time to help me out, but I'd suggesting making the documentation somewhat more explicit, e.g. link the example you sent me.

**Comment by raniejade** [comment] 2017-07-07 11:44
Yeah, `1.0.0-M5` was just recently released and it seems they introduced  several breaking changes again.

**Comment by RuudPaulissen** [comment] 2017-07-07 12:02
I've ran into another interesting issue here. If I run the tests manually, in IntelliJ, they all pass and everything is fine. However, if I run them through maven, I get a NullPointerException thrown from the surefire plugin.

Could this be a bug?

**Comment by raniejade** [comment] 2017-07-07 16:33
Can you paste the stacktrace?

**Comment by RuudPaulissen** [comment] 2017-07-07 21:25
Hi, there is no stack trace, really. In attachment I've added the output of the Surefire test run from Maven. It signals a failure, with a "null" value appearing in the console. That's about all error message I'm getting.
<img width="1044" alt="schermafbeelding 2017-07-07 om 23 14 38" src="https://user-images.githubusercontent.com/29971665/27977501-54b2c076-636b-11e7-8555-28353ca1d99d.png">

When running it directly, without Maven intervening, all of my tests do pass.

**Comment by RuudPaulissen** [comment] 2017-07-10 21:38
Take back what I last said about there not being a full stack trace: I've been looking into the issue some more and overlooked the "-e" tag for Maven.

Anyways, here is het full stack trace.
![schermafbeelding 2017-07-10 om 23 35 13](https://user-images.githubusercontent.com/29971665/28041207-d015867c-65c8-11e7-80ed-4f4bbe8de3e8.png)

Thanks in advance.

**Comment by RuudPaulissen** [comment] 2017-07-10 21:57
I have found an issue with the exact same error and stack trace as me, here in the spek issues catalog. Link: https://github.com/JetBrains/spek/issues/138.

There was no real solution found, besides adding the @runwith(JUnitPlatform::class) annotation to every test class. Is this still the best way to solve this error?

**Comment by raniejade** [comment] 2017-07-11 08:35
What version of maven are you using?

**Comment by RuudPaulissen** [comment] 2017-07-11 08:38
Maven version 3.3.9, Java 1.8.0_111, Mac OS X 10.12.5

**Comment by raniejade** [comment] 2017-07-11 08:40
I saw your bug report https://issues.apache.org/jira/browse/SUREFIRE-1388, let's wait for a reply from the surefire team.

**Comment by Ritzzzll** [comment] 2017-07-14 21:10
@raniejade the error messages I'm having are exactly those the issuer of ticket https://github.com/JetBrains/spek/issues/138 is having. He resolved vis issues by adding the @RunWith annotation, only I don't seem to have the necessary dependecies for JUnitPlatform::class. Do you have any experience with this?

**Comment by RuudPaulissen** [comment] 2017-07-14 21:14
@raniejade the error messages I'm having are exactly those the issuer of ticket https://github.com/JetBrains/spek/issues/138 is having. He resolved vis issues by adding the @runwith annotation, only I don't seem to have the necessary dependecies for JUnitPlatform::class. Do you have any experience with this?

**Comment by raniejade** [comment] 2017-07-16 03:00
@RuudPaulissen you need `org.junit.platform:junit-platform-runner`.

**Comment by RuudPaulissen** [comment] 2017-07-18 06:00
No luck, will have to continue playing the waiting game I guess.

**Comment by raniejade** [comment] 2017-07-18 06:25
Can you upload a sample project (in github) that reproduces the issue? I'll try to test it out again, it's been awhile since I used maven :).

**Comment by RuudPaulissen** [comment] 2017-07-19 17:20
Thank you for willing to take the time to look into it, @raniejade :-)
I'll do my best to prep something in the next few days. The weird thing is that the errors seem to occur in tests that come with external dependencies (e.g. database connectivity, network connectivity, ...) so it's not that straightforward to reproduce I fear.

**Comment by inikolaev** [comment] 2017-09-27 20:10
Hi, I'm also having trouble using spek with latest versions of dependencies. I've created a sample repository to reproduce the issue: https://github.com/inikolaev/kotlin-spek-maven-example

Let me know if you are able to reproduce the issue when running it.

**Comment by inikolaev** [comment] 2017-09-27 20:32
I also added `Dockerfile` so it would be easier to reproduce it.

**Comment by raniejade** [comment] 2017-09-28 04:46
Thanks, I'll look into it this weekend!

**Comment by raniejade** [comment] 2017-09-30 04:36
@inikolaev Looks like there's an issue with JUnit Platform and Surefire `2.20.1`. I've tried using `2.19` as mentioned in the JUnit docs and it works. Below is the changes I made (it includes some cleanup).

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.github.inikolaev</groupId>
    <artifactId>spek</artifactId>
    <version>1.0</version>

    <dependencies>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>1.1.50</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-reflect</artifactId>
            <version>1.1.50</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-test-junit</artifactId>
            <version>1.1.50</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.spek</groupId>
            <artifactId>spek-api</artifactId>
            <version>1.1.5</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.0.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>1.1.50</version>
                <configuration>
                    <jvmTarget>1.8</jvmTarget>
                </configuration>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <sourceDirs>
                                <source>src/main/java</source>
                                <source>src/main/kotlin</source>
                            </sourceDirs>
                        </configuration>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <phase>process-test-sources</phase>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                        <configuration>
                            <sourceDirs>
                                <source>src/test/java</source>
                                <source>src/test/kotlin</source>
                            </sourceDirs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.6.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>

                <executions>
                    <!-- Replacing default-compile as it is treated specially by maven -->
                    <execution>
                        <id>default-compile</id>
                        <phase>none</phase>
                    </execution>
                    <!-- Replacing default-testCompile as it is treated specially by maven -->
                    <execution>
                        <id>default-testCompile</id>
                        <phase>none</phase>
                    </execution>
                    <execution>
                        <id>java-compile</id>
                        <phase>compile</phase>
                        <goals> <goal>compile</goal> </goals>
                    </execution>
                    <execution>
                        <id>java-test-compile</id>
                        <phase>test-compile</phase>
                        <goals> <goal>testCompile</goal> </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.19</version>
                <dependencies>
                    <dependency>
                        <groupId>org.junit.platform</groupId>
                        <artifactId>junit-platform-surefire-provider</artifactId>
                        <version>1.0.0</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jetbrains.spek</groupId>
                        <artifactId>spek-junit-platform-engine</artifactId>
                        <version>1.1.5</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <includes>
                        <include>**/*Spek.*</include>
                    </includes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

```

**Comment by raniejade** [comment] 2017-09-30 04:38
For reference: https://github.com/junit-team/junit5/issues/809

**Comment by raniejade** [comment] 2017-09-30 04:39
Looks like it's not an issue w/ Spek. Closing it now, re-open if I miss something.

**Closed by raniejade** 2017-09-30 04:39 UTC
