### ISSUE TITLE
java.lang.IllegalStateException: it.javaClass.`package` must not be null

### ISSUE THREAD

**Issue by NikkyAI** [JetBrains/spek#615] opened 2019-02-06 09:46 UTC
i updated to 2.0.0 and i got this: ![https://i.imgur.com/SkeXjL8.png](https://i.imgur.com/SkeXjL8.png)

note that none of my tests are in the root package

```
Feb 06, 2019 5:52:02 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'spek2' failed to discover tests
java.lang.IllegalStateException: it.javaClass.`package` must not be null
    at org.spekframework.spek2.junit.SpekTestEngine.discover(SpekTestEngine.kt:51)
    at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:168)
    at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:155)
    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
    at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:102)
    at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:82)
    at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:78)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.stop(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
    at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
    at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
    at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by raniejade** [comment] 2019-02-06 10:15
Duplicate of #574.

This has been eluding me for awhile now, I can't seem to replicate it. Initial theory is it has something to do with either the jvm version or `kotlin-reflect`.

**Closed as completed by raniejade** 2019-02-06 10:15 UTC
Labels: is: duplicate

**Comment by raniejade** [comment] 2019-02-06 10:56
@NikkyAI can you give me the following info:
- kotlin version
- kotlin reflect version (if you can give me the output of `./gradlew dependencies` - it will be awesome)
- java version

Are you able to share a sample project that replicates the issue consistently?

**Comment by NikkyAI** [comment] 2019-02-06 11:33
- Kotlin `1.3.20`
- Kotlin Reflect `1.3.20`
- java `openjdk version "1.8.0_192"`

output of dependencies: https://gist.github.com/NikkyAI/7229b2e7009881cb7906a51efe2799f7

**Comment by NikkyAI** [comment] 2019-02-06 11:36
tomorrow i will try to make a minimal project .. or try to remove reflect from my codebase.. it should not actually be required.. i hope

**Comment by raniejade** [comment] 2019-02-06 13:00
@NikkyAI was able to replicate it, see #574 (lets move the discussion there).
