### ISSUE TITLE
Add ability to 'go to test definition'

### ISSUE THREAD

**Issue by igorwojda** [JetBrains/spek#233] opened 2017-08-02 10:45 UTC
After running, JUnit tests we can click on the test result and test source File will be opened (proper line selected, line where the test is defined). I wonder can we add it to Spek?

![image](https://user-images.githubusercontent.com/530122/28870265-8217663c-7777-11e7-9fd4-aad0be076723.png)

Small improvement but it will improve testing a lot

**Comment by raniejade** [comment] 2017-08-02 21:56
Closing this as a duplicate of https://github.com/raniejade/spek-idea-plugin/issues/5.

**Closed by raniejade** 2017-08-02 21:56 UTC
