### ISSUE TITLE
memoized not obeying group scope

### ISSUE THREAD

**Issue by pdvrieze** [JetBrains/spek#165] opened 2017-01-19 13:10 UTC
In 1.1 beta 3 memoized (and therefore subjectspek) will not obey the group scope. As such the object cache is cleared after every group, not only the group in which the item is declared (or top scope in case of subjectspek). This behaviour is rather surprising and should probably be fixed checking the group parameter against a field assigned on construction.

**Comment by raniejade** [comment] 2017-01-19 14:31
When using  `CachingMode.GROUP` every group declared in the scope where the memoized value is created will have it's own instance, this is the intended behavior.

```kotlin
object MySpec: Spek({
   val value by memoized(CachingMode.GROUP) { Foo() }

   group("group1") {
     ...

     // value cleared here
   }

   group("group2") {
      ...

      // value cleared here again
   }
})
```

I guess what you want is to keep the instance until it goes out of scope. We could introduce `CachingMode.SCOPE` to support that.

```kotlin
object MySpec: Spek({
   val value by memoized(CachingMode.GROUP) { Foo() }

   group("group1") {
     ...
   }

   group("group2") {
      ...
   }

  // value cleared here only
})
```

**Comment by pdvrieze** [comment] 2017-01-23 11:20
Perhaps scope would be the correct way to do it. As long as this scope could also mean a group itself. I also find that beforeGroup actually has the semantics I want so there is some bit of confusion.

**Comment by raniejade** [comment] 2017-01-23 11:38
@pdvrieze I can see the confusion there, but I guess we could fix this by properly documenting the behaviour.

**Comment by raniejade** [comment] 2017-02-19 02:43
@artem-zinnatullin @hhariri can you guys weigh in :)

**Comment by artem-zinnatullin** [comment] 2017-02-19 16:57
Hm, my view probably is too conservative, but I'm actually against any state sharing in tests so each subject/memoized will be in a clean state for each test to prevent shooting yourself in the foot…

But, if you want that, I guess, `CachingMode.SCOPE` suggested by @raniejade is best way to achieve that without affecting behavior of previously supported modes.

**Closed** 2017-03-09 14:16 UTC
