### ISSUE TITLE
Initialization before each Scenario in Gherkin style

### ISSUE THREAD

**Issue by anschnapp** [JetBrains/spek#659] opened 2019-03-21 10:21 UTC
I want to make a fresh creation of my service together with some mocks. Before each "test", i'm using the Gherkin style.

A test in this context is for me every Scenario I have described.

I have tried beforeEachTest but this is also executed for every given- and when- then-sections. This is not suitable for me because i configure the mock behaviour inside the given blocks.

Then I have tried beforeGroup this is not executed for Scenario's because only Features are counting as groups.

Is there another possibility I don't have tried/found so far.
I guess it's quite a common use case to have something for each Scenario if you are using Gherkin style.

**Comment by anschnapp** [comment] 2019-03-21 10:25
Addition: Also the Feature are not counting as a group. Only a real `group` counts and this can be only created on the "root" level of the structure.

**Comment by rvega-arg** [comment] 2019-07-30 15:23
@anschnapp did you find any solution or workaround? we are struggling with the same issue

**Comment by raniejade** [comment] 2019-07-31 11:57
Closing as duplicate of #670.

**Closed as completed by raniejade** 2019-07-31 11:57 UTC
Labels: is: duplicate, status: invalid
