### ISSUE TITLE
Incorrect tests are runned from IDE

### ISSUE THREAD

**Issue by igorwojda** [JetBrains/spek#234] opened 2017-08-02 10:48 UTC
Clicking on the green arrow next to first `on` block runs only test inside this `on` block - OK
Clicking on the green arrow next to first `it` block runs all the tests instead of the only test defined inside this `it` block. I would expect that only test defined inside 'it' block will be runned

![image](https://user-images.githubusercontent.com/530122/28870452-40fb167a-7778-11e7-905e-28759979ff67.png)

**Comment by raniejade** [comment] 2017-08-02 21:58
Duplicate of https://github.com/raniejade/spek-idea-plugin/issues/34. `it`s inside on are only discovered during the execution phase so the runtime does not know about it when planning the test tree. The plugin should hide the gutter icons of `it`s when inside an `on`.

**Closed** 2017-08-07 09:51 UTC
